### ISSUE TITLE
No microphone

### ISSUE THREAD

**Issue by hmlendea** [szszoke/sennheiser-gsp670-pulseaudio-profile#1]
Stereo seems to work fine after installing this, however this headset is now missing completely from the input devices dropdown.

**Comment by hmlendea** [comment]
Ok, this is really weird. Apparently it still works inside of my apps.

Might be an issue with GNOME / GNOME Settings then? Because it works fine in Discord.

In any case, I'm gonna close this issue.
Sorry to bother you.

**Comment by szszoke** [comment]
PulseAudio will generate the a few profiles for the headset with the various sinks and sources.

It could be that you had one selected where only the main output was enabled.

There should be a profile where the main output, the communication input and output are enabled at the same time.

**Comment by hmlendea** [comment]
Yep, I've noticed after taking a look at the files and trying to understand how they work.
Initially I expected the input to be selected individually regardless of the output.

They seem to work just fine.
Awesome repository, you really saved me here. Thanks!

**Comment by szszoke** [comment]
Hey!

I was testing your PR under manjaro and I encountered the issue you described. I will look into it a bit more.

It was not an issue under Kubuntu, there I could choose the Input and Output independently.

**Comment by hmlendea** [comment]
Hey, I've seen that you've reopened this issue. Good :P I have new findings.

Because the microphone is not listed as an input source, it won't be listed in games either.

Usually I use Discord to chat with my friends, and it works there just fine. Most likely Discord detects input sources its own way, which would make sense since it's a dedicated voice chat app.


However, I was playing Garry's Mod with a friend and I wanted to use the in-game chat to say something on the server, when I was told that I was on "mute" and no voice came through. Now the game doesn't have a setting to switch the input source, so I assume it just uses whatever I have selected in my system settings (IMO it makes perfect sense to be that way), and this is where the problem resides.

By the way, I'm using Arch Linux. I'm curious if this is an issue for other distro families as well? You've said Kubuntu works fine, which is based on Ubuntu, but Manjaro which is based on Arch doesn't.
I don't really have experience with Ubuntu, and especially Kubuntu, so I don't know all the differences, but could it be that Arch-based systems have a newer PA version which does things differently? IDK, I can only guess.
Or who knows, it might be a GNOME issue, what DE did you use on Manjaro? It wouldn't be the first time GNOME messes with PA in my experience.

**Comment by szszoke** [comment]
I have a fix for this that works for on my system. I will create a PR soon and I would like to ask you to test it on your machine.

I will try it with Ubuntu in a VM or with a live system too.

**Comment by hmlendea** [comment]
Seems to be working fine. I can select the input in the Settings now, and I can also use it independently of the output setting.

I think it solved the problem completely.

**Comment by szszoke** [comment]
The fix for this was included in the 1.2 release.
