### ISSUE TITLE
Would this work for the Sennheiser GSP 370?

### ISSUE THREAD

**Issue by x10an14** [szszoke/sennheiser-gsp670-pulseaudio-profile#11]
Hi!

Thanks so much for your OSS efforts!

Would you happen to know if this would work with a GSP 370 headset?
Would like to enable the "Binaurality" of that headset^^

It currently only shows up as Mono output in Pulseaudio/Pavucontrol.
![Screenshot from 2021-03-27 17-00-19](https://user-images.githubusercontent.com/710608/112726469-fa3c2000-8f1d-11eb-8978-f9e8e6938530.png)

PS: If you suspect it won't, got any tips on what to search for look/for?

**Comment by szszoke** [comment]
The only way I think it would work if it is implemented via hardware and we can find a way to turn it on.

If it is done in software then you will need some kind of plugin to replicate that with PulseAudio.

**Comment by x10an14** [comment]
Oh, okay =) Thanks for your time and answer!
