### ISSUE TITLE
system sound through hdmi and all other sound on gsp670

### ISSUE THREAD

**Issue by joulester** [szszoke/sennheiser-gsp670-pulseaudio-profile#16]
I have a strange issue with my sound and that is some sound still uses my hdmi connections to my screens but all settings under sound says headphones - EPOS GS 70 with config Chat Output - Game Output - Chat input. 

I followed @Akselmo how to get it to work [https://github.com/szszoke/sennheiser-gsp670-pulseaudio-profile/issues/13#issuecomment-898555895](url)

Anybody who has the same problem?

**Comment by joulester** [comment]
I'm using pop os 21.04 and when I'm testing my out put device I here it from my hdmi screen.
![image](https://user-images.githubusercontent.com/19240362/137626356-17167793-7d45-48df-9736-ccdc514ebdfd.png)

**Comment by szszoke** [comment]
Some applications can choose a specific sound device and use that instead of the system default.

Which applications are affected?

**Comment by joulester** [comment]
I solved it with Pavucontrol and disabled the hdmi out and now all sound goes over the headset.
