### ISSUE TITLE
Headset is a constant battle to keep on

### ISSUE THREAD

**Issue by Rosentti** [szszoke/sennheiser-gsp670-pulseaudio-profile#20]
When starting the system, the headset works quite well. However, it just stops working randomly and one or many of these will fix it sometimes:
- restaring pipewire, pipewire-pulse, wireplumber
- unplugging and replugging the dongle
- switching the dongle's profile to "off" and back to previous
And sometimes none of these work and a reboot is needed. 
The system logs are spammed with approximately 5 of these a second:
```
8.7.2022 17.46	pipewire	spa.alsa: hw:2,0,0: snd_pcm_avail after recover: Broken pipe
```
I am using the linux-zen kernel. Maybe it has something to do with this? Either way, I really don't know how to go about debugging this. And I don't know where to get help with this.

**Comment by szszoke** [comment]
Hey!

I am not sure which kernel and pipewire version you are using but if it is anything from 2022 then you likely don't need this profile.

**Comment by szszoke** [comment]
See the update in README.md
