### ISSUE TITLE
Send paypal information for donation

### ISSUE THREAD

**Issue by luisalvarado** [szszoke/sennheiser-gsp670-pulseaudio-profile#4]
Hi buddy, I have purchased the SteelSeries Arctis 7, Logitech Headset G930 & Logitech G633 Artemis. All of the them having the SAME issue as you are fixing in this pulseaudio profile. I will be purchasing this specific Sennheiser model next month and if it works well with your profile I will like to send you a donation because you will be making my life MUCH BETTER for work and play.

**Comment by szszoke** [comment]
Hey!

Hopefully you will have more luck with your Sennheiser headset. Let me know if you have issues.

I am grateful and I really appreciate that you want to send me a donation! With everything going on right now I would rather see that money go towards a charity or someone in need. I am lucky enough to still have a job and I feel that there are better destinations for that donation than my pocket.

If you still have the Arctics 7 you might want to take a look at this PulseAudio profile: https://github.com/bobbyrward/steelseries-arctis-7-pulseaudio-profile

I haven't tried it myself but it might solve your problems.

Cheers,
Szabi

**Comment by luisalvarado** [comment]
Thank you again @szszoke will do friend.
