### ISSUE TITLE
Pipewire

### ISSUE THREAD

**Issue by torvitas** [szszoke/sennheiser-gsp670-pulseaudio-profile#8]
Hi,

thanks for this project.
I could not yet figure out how to apply this profile when using pipewire-pulseaudio.
Could you maybe add some information regarding pipewire?

/Sascha

**Comment by szszoke** [comment]
PipeWire is uncharted territory for me unfortunately. I have a setup that works with Jack and ALSA and I haven't taken experiment yet.

I can't promise anything regarding when I would do experiments with PipeWire.

If you have something to share, please post it on this ticket.

**Comment by torvitas** [comment]
I need this headset for my daily business so I rolled back to pulseaudio for now. I might give it another try the upcoming week end.
Thanks for the feedback!

**Comment by lethalwp** [comment]
don't know if it helps, but i think i had the same issue when upgrading today from Fedora33 to the alpha F34. They switched from pulse to default pipewire.

To make it work again, i had to copy the conf files from /usr/share/pulseaudio/alsa-mixer to /usr/share/alsa-card-profile/mixer

and patch the udev file, changing: 
ATTRS{idVendor}=="1395", ATTRS{idProduct}=="0089", ENV{PULSE_PROFILE_SET}="sennheiser-gsp670-usb-audio.conf"
ATTRS{idVendor}=="1395", ATTRS{idProduct}=="008a", ENV{PULSE_PROFILE_SET}="sennheiser-gsp670-usb-audio.conf"

to: 
ATTRS{idVendor}=="1395", ATTRS{idProduct}=="0089", ENV{ACP_PROFILE_SET}="sennheiser-gsp670-usb-audio.conf"
ATTRS{idVendor}=="1395", ATTRS{idProduct}=="008a", ENV{ACP_PROFILE_SET}="sennheiser-gsp670-usb-audio.conf"

Then a reboot and it worked as previously :)

**Comment by torvitas** [comment]
@szszoke - are you interested in integrating pipewire support?

**Comment by szszoke** [comment]
I'm not opposed but it is not something I can work on in the foreseeable future.

You are welcome to submit a PR though.

**Comment by torvitas** [comment]
I would happily submit a PR, though I am not sure how to integrate the change. Do you have any idea how you would go about this?

I could just provision both folders by putting some symlinks at /usr/share/alsa-card-profile/mixer. But I am not sure how to go about the udev file.

An alternative approach would be to just add some information regarding pipewire to the readme.

**Comment by szszoke** [comment]
Can't we just have both `ENV{PULSE_PROFILE_SET}` and `ENV{ACP_PROFILE_SET}` at the same time in the udev file?

**Comment by lethalwp** [comment]
- It worked for me last week.
- But fedora 34 got some major updates : 2021-02-22T09:34:53+0100 DEBUG ---> Package pipewire-libs.x86_64 0.3.22-1.fc34 will be upgraded

Now it seems those files are not required anymore to have a "gsa 70 Pro" profile. that appeared.
It works well for playing, but the mic is choppy.

I don't know (yet) if the gsp670 files are still needed

**Comment by szszoke** [comment]
I updated my Manjaro system today and I also noticed the same. Let's continue this in #18. I will close this issue for now.
